apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-read-and-build
  namespace: cicd
spec:
  description: |
    This pipeline clones a git repo, then echoes the README file to the stdout.
  params:
    - name: repo-url
      type: string
      description: The git repo URL to clone from.
    - name: env-repo-url
      type: string
      description: The git repo URL to clone from.
    - name: image-reference
      type: string
    - name: stage
      type: string
      description: Stage that will be deployed to
    - name: path-to-patch-file
      type: string
  workspaces:
    - name: shared-data
      description: |
        This workspace contains the cloned repo files, so they can be read by the
        next task.
    - name: basic-auth
      description: |
        This workspace contains the basic-auth for gitea
    - name: env-repo
      description: |
        This workspace contains the env repo files, so they can be read by the
        next task.
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
        - name: basic-auth
          workspace: basic-auth
      params:
        - name: url
          value: $(params.repo-url)
    - name: build-app
      runAfter: ["fetch-source"]
      workspaces:
        - name: source
          workspace: shared-data
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: registry-service.infrastructure:5000/$(params.image-reference)
        - name: EXTRA_ARGS
          value:
          - "--insecure"
          - "--insecure-pull"
          - "--insecure-registry=registry-service.infrastructure:5000"
    - name: fetch-env-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: env-repo
        - name: basic-auth
          workspace: basic-auth
      params:
        - name: url
          value: "$(params.env-repo-url)"
    - name: kustomize-deployment
      runAfter: ["fetch-env-source", "build-app"]
      taskRef:
        name: cd-deploy-task
      workspaces:
        - name: git-source
          workspace: env-repo
      params:
        - name: path-to-patch-file
          value: $(params.path-to-patch-file)
        - name: image-reference
          value: localhost:30050/$(params.image-reference)
        - name: stage
          value: $(params.stage)