apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
spec:
  addon: { }
  config: { }
  dashboard:
    readonly: false
  hub: { }
  pipeline:
    await-sidecar-readiness: true
    disable-affinity-assistant: true
    disable-creds-init: false
    embedded-status: full
    enable-api-fields: stable
    enable-bundles-resolver: true
    enable-cluster-resolver: true
    enable-custom-tasks: false
    enable-git-resolver: true
    enable-hub-resolver: true
    enable-provenance-in-status: false
    enable-tekton-oci-bundles: false
    metrics.pipelinerun.duration-type: histogram
    metrics.pipelinerun.level: pipeline
    metrics.taskrun.duration-type: histogram
    metrics.taskrun.level: task
    require-git-ssh-secret-known-hosts: false
    running-in-environment-with-injected-sidecars: true
    send-cloudevents-for-runs: false
    verification-mode: skip
  platforms:
    openshift: { }
  profile: all
  pruner:
    keep: 100
    resources:
      - pipelinerun
    schedule: 0 8 * * *
  targetNamespace: tekton-pipelines
  trigger:
    enable-api-fields: stable
    